import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generatePDFReport = async (reportData, query) => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Helper function to add text with word wrap
  const addText = (text, fontSize = 12, fontStyle = 'normal') => {
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', fontStyle);
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    
    lines.forEach(line => {
      if (yPosition > pageHeight - margin) {
        pdf.addPage();
        yPosition = margin;
      }
      pdf.text(line, margin, yPosition);
      yPosition += fontSize * 0.5 + 2;
    });
    
    return yPosition;
  };

  // Helper function to add section header
  const addSectionHeader = (title) => {
    yPosition += 10;
    addText(title, 16, 'bold');
    yPosition += 5;
    pdf.setDrawColor(59, 130, 246);
    pdf.setLineWidth(0.5);
    pdf.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;
  };

  // Title Page
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Enterprise Agents Platform', pageWidth / 2, 60, { align: 'center' });
  
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Research Report', pageWidth / 2, 80, { align: 'center' });
  
  pdf.setFontSize(14);
  pdf.text(`Query: "${query}"`, pageWidth / 2, 100, { align: 'center' });
  
  pdf.setFontSize(12);
  pdf.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, 120, { align: 'center' });
  
  // Add new page for content
  pdf.addPage();
  yPosition = margin;

  // Table of Contents
  addSectionHeader('Table of Contents');
  addText('1. Executive Summary');
  addText('2. Research Findings');
  addText('3. Analysis Results');
  addText('4. Final Report');
  addText('5. Sources & References');

  // Research Section
  pdf.addPage();
  yPosition = margin;
  addSectionHeader('1. Research Findings');
  
  if (reportData.research) {
    addText(`Processing Time: ${reportData.research.processing_time}ms`);
    addText(`Request ID: ${reportData.research.request_id || 'N/A'}`);
    yPosition += 10;
    addText(reportData.research.content || 'No research content available');
    
    if (reportData.research.sources && reportData.research.sources.length > 0) {
      yPosition += 10;
      addText('Sources:', 14, 'bold');
      reportData.research.sources.forEach(source => {
        addText(`• ${source}`);
      });
    }
  }

  // Analysis Section
  pdf.addPage();
  yPosition = margin;
  addSectionHeader('2. Analysis Results');
  
  if (reportData.analysis) {
    addText(`Processing Time: ${reportData.analysis.processing_time}ms`);
    addText(`Confidence Level: ${reportData.analysis.confidence || 'N/A'}`);
    yPosition += 10;
    addText(reportData.analysis.content || 'No analysis content available');
    
    if (reportData.analysis.insights && reportData.analysis.insights.length > 0) {
      yPosition += 10;
      addText('Key Insights:', 14, 'bold');
      reportData.analysis.insights.forEach(insight => {
        addText(`• ${insight}`);
      });
    }
  }

  // Final Report Section
  pdf.addPage();
  yPosition = margin;
  addSectionHeader('3. Final Report');
  
  if (reportData.report) {
    addText(`Report Type: ${reportData.report.report_type || 'N/A'}`);
    addText(`Generated: ${reportData.report.timestamp || 'N/A'}`);
    addText(`Processing Time: ${reportData.report.processing_time}ms`);
    yPosition += 10;
    addText(reportData.report.content || 'No report content available');
  }

  // Footer on each page
  const totalPages = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'italic');
    pdf.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    pdf.text('Generated by Enterprise Agents Platform', margin, pageHeight - 10);
  }

  // Save the PDF
  const fileName = `research_report_${query.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}.pdf`;
  pdf.save(fileName);
  
  return fileName;
};

export const generateQuickPDF = async (elementId, fileName) => {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error('Element not found');
  }

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    allowTaint: true,
  });

  const imgData = canvas.toDataURL('image/png');
  const pdf = new jsPDF('p', 'mm', 'a4');
  const imgWidth = 210;
  const pageHeight = 295;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;
  let heightLeft = imgHeight;

  let position = 0;

  pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
  heightLeft -= pageHeight;

  while (heightLeft >= 0) {
    position = heightLeft - imgHeight;
    pdf.addPage();
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
  }

  pdf.save(fileName);
};
